[models]

[models.one]
name = "EleutherAI/gpt-j-6b"

[models.one.rename]
transformer = "model"
h = "layers"

[models.two]
name = "meta-llama/Meta-Llama-3.1-8B"

[models.two.rename]
norm = "ln_f"

[models.three]
name = "meta-llama/Meta-Llama-3.1-8B-Instruct"

[models.three.rename]
norm = "ln_f"